version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: listatareas-api
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/listatareasdb
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  mongo:
    image: mongo:7
    container_name: listatareas-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
